[workspace]
members = [
    "legion-prefab",
    "legion-transaction",
    "prefab-format",
]

[patch.crates-io]
#legion = { path = "legion" }
legion = { git = "https://github.com/aclysma/legion.git", branch = "legion-0.3-prefab-support" }